### ISSUE TITLE
HW 10.10.2016 Tests

### ISSUE THREAD

**Issue by alxanko** [deniotokiari/training-epam-2016#100]
Alexey Khanko
https://github.com/chelsenok/MT
sorry for folder .idea, i have it in my .gitignore

**Comment by alexdzeshko** [comment]
remove it from vcs

**Comment by alxanko** [comment]
done with help of git console

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that today on class)

**Comment by alxanko** [comment]
ok
https://github.com/chelsenok/MT/commit/0fa8516525e8f194fda0c8cef3460c0a58f7b55c

**Comment by ilya-shknaj** [comment]
ok
