### ISSUE TITLE
HW-12.10.2016 Backend

### ISSUE THREAD

**Issue by kovac777** [deniotokiari/training-epam-2016#102]
https://github.com/kovac777/HW-12.10.2016
Maksim Vinnik

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that today on class)

**Comment by kovac777** [comment]
https://github.com/kovac777/HW-12.10.2016/commit/0035b26502dad4cf5eef6d1ffe6cbaecc44f6dfe

**Comment by ilya-shknaj** [comment]
ok
