### ISSUE TITLE
HW 05.10.2016 Static layout

### ISSUE THREAD

**Issue by kovac777** [deniotokiari/training-epam-2016#103]
https://github.com/kovac777/HW-05.10.2016-Static-Layout
Maksim Vinnik

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that today on class)

**Comment by kovac777** [comment]
https://github.com/kovac777/HW-05.10.2016-07.10.2016/commit/ad0ca76469c7e2b56d8778a781df868b16eb9222

**Comment by kovac777** [comment]
https://github.com/kovac777/HW-05.10.2016-07.10.2016/commit/326b990fcad7e0433962f673645d857df8fe4c98

**Comment by ilya-shknaj** [comment]
ok
