### ISSUE TITLE
HW: 12.10.2016 App Engine

### ISSUE THREAD

**Issue by zagart** [deniotokiari/training-epam-2016#104]
[App Engine module.</li>](https://github.com/zagart/observer-android/commit/1c1b153e0551bb4aa811e2870a0d4524bc6133ea)
[Endpoints sample (gradle-appengine-templates).](https://github.com/zagart/observer-android/commit/140ee1780937282a22a3434976709d0de8fd5e69)
[Live backend deployment.](https://github.com/zagart/observer-android/commit/b1b87ca454d78a198a05a24fa94e0944ad8387f3)

**Comment by ilya-shknaj** [comment]
ok
