### ISSUE TITLE
Training Project + HW 12.10.2016.

### ISSUE THREAD

**Issue by Hanna-Kokhanava** [deniotokiari/training-epam-2016#105]
Repository with training project. With client-backend connection already. Also, data receiving from Firebase is implemented.
https://github.com/Anna-Kohanova/HotelRoomsReservation

**Comment by ilya-shknaj** [comment]
I have compilation error.

Error:Execution failed for task ':app:processDebugGoogleServices'.

> File google-services.json is missing. The Google Services Plugin cannot function without it. 
>    Searched Location: 
>   /Users/ilya.shknaj/Android/workspace/Training/HotelRoomsReservation/app/src/debug/google-services.json
>   /Users/ilya.shknaj/Android/workspace/Training/HotelRoomsReservation/app/google-services.json

**Comment by ilya-shknaj** [comment]
Code looks good. I added few TODOs https://github.com/Anna-Kohanova/HotelRoomsReservation/commit/4b48cf7d6603ce863dac674b7e7f29762db88f14

**Comment by Hanna-Kokhanava** [comment]
Thank you for your comments, soon I will fix it.
You have such a funny situation with compilation error, because I have necessary "google-services.json" file in .gitignore, sorry :D

**Comment by Hanna-Kokhanava** [comment]
Fixed TODOs : https://github.com/Anna-Kohanova/HotelRoomsReservation/commit/2ff418feafb1d38fb87ae2d79c02b08c7ed936d7

google-services.json file is deleted from .gitignore now. You can try to test my code again.
