### ISSUE TITLE
Training project flowchart & description

### ISSUE THREAD

**Issue by zagart** [deniotokiari/training-epam-2016#109]
[See readme.](https://github.com/zagart/observer-android/blob/master/README.md)

**Comment by ilya-shknaj** [comment]
scheme looks good. After today class do you have more questions about that?

**Comment by zagart** [comment]
Right now I enough far from establishing connection between backend and client. But for now with your help I got answers for most of questions that I had before and them more then necessary for current work, thank you :)
But I think during future work I will have more questions , so I hope on you help!

**Comment by ilya-shknaj** [comment]
ok, feel free ask questions
