### ISSUE TITLE
HW  Activity 03.10.16

### ISSUE THREAD

**Issue by qerlly** [deniotokiari/training-epam-2016#11]
https://github.com/qerlly/ActivityE

**Comment by ilya-shknaj** [comment]
Bad solution override method onKeyDown. Use flags https://developer.android.com/reference/android/content/Intent.html#

**Comment by qerlly** [comment]
Remade https://github.com/qerlly/ActivityE/commit/a5bd18132106c3a87e61bdc32334f4e156d8986d

**Comment by ilya-shknaj** [comment]
ok
