### ISSUE TITLE
HW 07.10.2016

### ISSUE THREAD

**Issue by kovac777** [deniotokiari/training-epam-2016#110]
https://github.com/kovac777/HW-05.10.2016-Static-Layout/commits/master
Maksim Vinnik

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that today on class)

**Comment by kovac777** [comment]
https://github.com/kovac777/HW-05.10.2016-07.10.2016/commit/ad0ca76469c7e2b56d8778a781df868b16eb9222

**Comment by kovac777** [comment]
https://github.com/kovac777/HW-05.10.2016-07.10.2016/commit/ad0ca76469c7e2b56d8778a781df868b16eb9222

**Comment by ilya-shknaj** [comment]
ok
