### ISSUE TITLE
HW 12.10.2016 AppEngine

### ISSUE THREAD

**Issue by alxanko** [deniotokiari/training-epam-2016#113]
Alexey Khanko
https://github.com/chelsenok/AppEngine/commit/066847f3a3783f9407c74f8d002e66b38717268c

**Comment by alexdzeshko** [comment]
remove /build
this is the last time I ask for this

**Comment by alxanko** [comment]
done

https://github.com/chelsenok/AppEngine/compare/066847f3a3783f9407c74f8d002e66b38717268c...master

**Comment by ilya-shknaj** [comment]
ok
