### ISSUE TITLE
HW: 17.10.2016 Gradle, Flavors 

### ISSUE THREAD

**Issue by KarsekaVladimir** [deniotokiari/training-epam-2016#114]
1, Create 4 flavors (for example 2 variants of enviroments and 2 variants of countries)
https://github.com/KarsekaVladimir/SocialSample/commit/efdf4bcbb1b0c496dd0b0b77c4c083676b87b6b1

https://github.com/KarsekaVladimir/SocialSample/commit/c8d6b1fe85ffb4f1840d9108d210eab7e613538c

2, rename apk over gradle task to app_name+flover+version
https://github.com/KarsekaVladimir/SocialSample/commit/239683aa2a39fa1b4152befa6256144e3748175c

**Comment by KarsekaVladimir** [comment]
3,define variables in gradle and use it in Java code
https://github.com/KarsekaVladimir/SocialSample/commit/013205385b2667afa87704b51ba8432afa0a32d7

**Comment by alexdzeshko** [comment]
1. Seems that you didn't get the point of flavors. Translations should be under corresponding folder (ex. values-ru). Try to some functionality into one of the flavors that won't be in the other flavor.
2. Task is to rename apk with regards to name, flavor and version ;)
3. Can't see usage

**Comment by KarsekaVladimir** [comment]
1. Thanks for your comments. I merged some branch, and unfortunately I can't find necessary  commit, because I  made screenshots. Yes I've got it - you spoke about Flavors, but I made different functionality through buildTypes, for group of Flavors. I hope it will be enough for closing first point of task
   https://www.dropbox.com/s/4vm372pdwzp11xw/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-10-14%2011.39.56.png?dl=0
   https://www.dropbox.com/s/uhgllw26s7byibg/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-10-14%2011.41.39.png?dl=0

**Comment by alexdzeshko** [comment]
I don't like the idea with closing this issue relying on screenshots😁 Try harder.

**Comment by KarsekaVladimir** [comment]
ok, Boss...
1. Create 4 flavors (for example 2 variants of enviroments and 2 variants of countries)
 https://github.com/KarsekaVladimir/ANDROID_SocialSample/commit/87c8e78f3fad8a685ca77ae8bd424431377dc9c0
3, Define variables in gradle and use it in Java code
https://github.com/KarsekaVladimir/ANDROID_SocialSample/commit/622d69e8034c47b3061da31b35a048c37ffc57a4

**Comment by KarsekaVladimir** [comment]
2, rename apk over gradle task to app_name+flover+version
https://github.com/KarsekaVladimir/ANDROID_SocialSample/commit/ee60edaeb7cf5c79345dc23335653fd1ea630995

**Comment by ilya-shknaj** [comment]
if i select flavor alphaRussia which applicationId i will have?

**Comment by KarsekaVladimir** [comment]
Thank for your question! You can get next apk name 
app-russia-alpha-debug socialsample.russiaAlpha 1.1
Thank for your patience.
