### ISSUE TITLE
HW Backend,Flover,Gradle

### ISSUE THREAD

**Issue by jenia996** [deniotokiari/training-epam-2016#121]
https://github.com/jenia996/ETraining/commit/5eb85b3260e5711f0fb6079ffc289b3aa334f413

**Comment by ilya-shknaj** [comment]
if you add class to debug mode (like DebugClass) you also should add that class to release mode, because if you try compile application in release mode you will have compilation error

**Comment by jenia996** [comment]
Fixes https://github.com/jenia996/ETraining/commit/485673cba0ec17fcc68cf7e5e05845e5ef2b593a

**Comment by ilya-shknaj** [comment]
what about renaming apk?

**Comment by jenia996** [comment]
Added  https://github.com/jenia996/ETraining/commit/1aa24bd7236116132d083c8d8508beb4714ce1a9
