### ISSUE TITLE
HW 17.10

### ISSUE THREAD

**Issue by Andrei1993ak** [deniotokiari/training-epam-2016#125]
https://github.com/Andrei1993ak/NewFAmilyFinances/commit/e3332772118093726439ec1288afa70e405d1be4

**Comment by Andrei1993ak** [comment]
HW 14.10 done at my 12.10 HW see
https://github.com/deniotokiari/training-epam-2016/issues/106

**Comment by ilya-shknaj** [comment]
HW 17.10 - ok
