### ISSUE TITLE
Question about patterns

### ISSUE THREAD

**Issue by AlexTheKing** [deniotokiari/training-epam-2016#129]
Good Afternoon, I have a question about Builder pattern.  
As we see an example last lesson, when we invoke builder, we write something like this:
`final House house = new House.Builder().setTitle("").setDoors("").setSize(0).build();`
I don't understand a little bit what is the advantage of using Builder, when we can just create getters/setters and write almost the same:  

```
House house = new House();
house.setTitle("");
house.setDoors("");
house.setSize(0);
house.build();
```

Or is it all about higher level abstraction?

**Comment by antonihnatovich** [comment]
Main idea of Builder Pattern is that you are not using your constructors directly, that will do a Builder class for you, also more suitable code style. 
final House house = new House.Builder().setTitle("").setDoors("").setSize(0).build();
Good profit of this pattern is that every "set" method returning a House object, so this give us a 
opportunity to run new method with help of just dot( outside the Builder class). More compact code and understandably. Just a guess.
If i wrong, correct me please.

**Comment by alexdzeshko** [comment]
Correct
