### ISSUE TITLE
HW Activity 03.10.16

### ISSUE THREAD

**Issue by SShopik** [deniotokiari/training-epam-2016#13]
https://github.com/SShopik/training_epam   -  app/

**Comment by ilya-shknaj** [comment]
If user successful finished registration (open Activity6) bad solution start Activity1-5 again after relaunch application

**Comment by SShopik** [comment]
If not to click button "clear history" will starts with Activity6 after relaunch application

**Comment by ilya-shknaj** [comment]
Ok, One more issues. If user finish registration (open Activity6) and run application again and tap back button he will see MainActivity. But in this case application should close

**Comment by SShopik** [comment]
add closing

**Comment by ilya-shknaj** [comment]
ok, but in this case better finish MainActivity instead of Activity6
