### ISSUE TITLE
HW 17.10.16 (Grandle, Flavours)

### ISSUE THREAD

**Issue by alaksiej-karalou** [deniotokiari/training-epam-2016#141]
https://github.com/Aliaksei-Karaliou/OneChat/commit/0018a7544846071dc898fc863199f096a659308d

**Comment by ilya-shknaj** [comment]
if you change buildType to release, you project will not compile because in release mode you don't have SOME_STRING variable

**Comment by Aliaksei-Karaliou** [comment]
e1ef12b

**Comment by alaksiej-karalou** [comment]
https://github.com/Aliaksei-Karaliou/OneChat/commit/e1ef12b9a15eec9d35cf2695ca99b36aa687db12
