### ISSUE TITLE
HW 05.10.2016. Trying to create static layout.

### ISSUE THREAD

**Issue by Hanna-Kokhanava** [deniotokiari/training-epam-2016#16]
https://github.com/Anna-Kohanova/EPAM-Project

**Comment by Hanna-Kokhanava** [comment]
Updated.

**Comment by IstiN** [comment]
Please reduce "white" backgrounds in views to avoid overdraw.
Images are not aligned in top. Try to use Percent\* layouts
Padding from top of images is too big

**Comment by Hanna-Kokhanava** [comment]
Hopefully, fixed this using Percent layouts. 
Now with reusable styles and attributes for HW 07.10.2016.
