### ISSUE TITLE
HW Layouts 03.10.16

### ISSUE THREAD

**Issue by Andrei1993ak** [deniotokiari/training-epam-2016#17]
https://github.com/Andrei1993ak/HW-Layouts-03.10.16

see Readme

**Comment by ilya-shknaj** [comment]
Looks very good, but i found few issues
1)in your case better use theme without actionBar instead calling actionBar.hide();
2) FrameLayout with id=content_frame can be removed
3) something wrong with your drawer https://dl.dropboxusercontent.com/u/51462228/Work/Untitled.png
4) Try avoid using deprecated methods like displ.getWidth(), displ.getHeight()

**Comment by Andrei1993ak** [comment]
fix all of them 
https://github.com/Andrei1993ak/HW-Layouts-03.10.16/commit/ff8d33be689f80fb2eae3a1e62064408a67d1112

**Comment by ilya-shknaj** [comment]
Good. Thanks

**Comment by Andrei1993ak** [comment]
And number 3 it is not a bug because of this layout is instead in FrameLayout with width 300dp (see activity main:368), in runtime all ok.
