### ISSUE TITLE
HW: 05.10.2016 Static layout + HW 07.10(IcButton/styles/Draw9Patch)

### ISSUE THREAD

**Issue by derzolew** [deniotokiari/training-epam-2016#31]
https://github.com/derzolew/hw-layout

**Comment by derzolew** [comment]
addition for HW 07.10.2016(about styles and IcButton) 
https://github.com/derzolew/hw-layout/commit/7c86b7294c43d7b89baa2baa835cc99892be29ad

HW 07.10.2016(about Draw9Patch)
https://github.com/derzolew/hw-9to-and-stuff

**Comment by IstiN** [comment]
Try RelativeLayouts and percents*
