### ISSUE TITLE
HW:05.10.16 Activities

### ISSUE THREAD

**Issue by Marhary** [deniotokiari/training-epam-2016#32]
A0:MainActivity A1:ActivityTwo  A2:ActivityTree ...
YES: next activity , NO:activity7 in ActivityTwo, in other previus act
https://github.com/Marhary/Marharyta_Bakun/tree/master/SaveActivity

**Comment by Marhary** [comment]
Styles and custom attributs are in Activities

**Comment by IstiN** [comment]
Please add flags in activities

**Comment by Marhary** [comment]
https://github.com/Marhary/Marharyta_Bakun/commit/68f176181467fa6d0b1251ff07e8d13d877319fa

I added

**Comment by ilya-shknaj** [comment]
ok
