### ISSUE TITLE
HW 05.10.16 Activities

### ISSUE THREAD

**Issue by anomalisfree** [deniotokiari/training-epam-2016#38]
Lisavets Aliaksandr
https://github.com/anomalisfree/for-epam/tree/test/LancheModeTest

**Comment by IstiN** [comment]
Please clear code, remove AppIndex related code

**Comment by anomalisfree** [comment]
https://github.com/anomalisfree/for-epam/commit/2fe7fb32d68dce27472ac859ca61598ef2784687
