### ISSUE TITLE
HW 05.10.2016 Static layout

### ISSUE THREAD

**Issue by anomalisfree** [deniotokiari/training-epam-2016#39]
Lisavets Aliaksandr
https://github.com/anomalisfree/for-epam/tree/test/Verstka

**Comment by IstiN** [comment]
Screenshots need to be in README.md

**Comment by anomalisfree** [comment]
https://github.com/anomalisfree/for-epam/commit/ac53c6709eed4ceaf4fae2f7da63bb65dac25d30

**Comment by ilya-shknaj** [comment]
i can't click on that links
also i can't find that links on your repository. I try use 'Screenshot_1475841855.png' for search

**Comment by ilya-shknaj** [comment]
?

**Comment by anomalisfree** [comment]
https://github.com/anomalisfree/for-epam/commit/3941382768afbbd073f01b02dd4ba743f9838e9e

**Comment by ilya-shknaj** [comment]
ok
