### ISSUE TITLE
HW 05.10.2016 Activities

### ISSUE THREAD

**Issue by maxcriser** [deniotokiari/training-epam-2016#46]
Maksim Zakharenka
https://github.com/maxcriser/EpamTrainingProject/tree/master/HW_Activities

**Comment by ilya-shknaj** [comment]
bad solution mark that login flow finished every time when MainActivity started;
better do that once when user finish login flow;
use java style for methods naming;
reuse one constant for putting and getting value from preferences

**Comment by maxcriser** [comment]
https://github.com/maxcriser/EpamTrainingProject/commit/a067600220fe9477d00e26592d9fa6273080744f

**Comment by ilya-shknaj** [comment]
ok
