### ISSUE TITLE
HW: Traning 2016

### ISSUE THREAD

**Issue by Pahanbl4** [deniotokiari/training-epam-2016#48]
Pavel Mankialevich
https://github.com/Pahanbl4/home

**Comment by ilya-shknaj** [comment]
use java style for naming methods and variables
bad solution mark login flow as complete every time when MainActivity launched. Better do that once, when user finish login flow.
if user finish login flow and tap back button on MainActivity he will see A5Activity.
Why you wrap button to relative layout?
MainActivity never call change_the_way method.

**Comment by ilya-shknaj** [comment]
?

**Comment by Pahanbl4** [comment]
https://github.com/Pahanbl4/home/tree/qwert
![image](https://cloud.githubusercontent.com/assets/22370107/19420210/3a5332f2-93ef-11e6-9fbe-6c4082c67b2d.png)
![image](https://cloud.githubusercontent.com/assets/22370107/19420218/50531ac2-93ef-11e6-8c67-bfd5c9679225.png)

**Comment by ilya-shknaj** [comment]
ok, but method name should start from lowercase letter
