### ISSUE TITLE
HW:05.10.2016

### ISSUE THREAD

**Issue by VERSTEHEN9** [deniotokiari/training-epam-2016#55]
https://github.com/VERSTEHEN9/restart

**Comment by ilya-shknaj** [comment]
please specify in which folder i can found hometask 05.10.216 and 07.10.2016

**Comment by ilya-shknaj** [comment]
?

**Comment by VERSTEHEN9** [comment]
https://github.com/VERSTEHEN9/restart/tree/master/HW_07 : HW 05.10.16
HW 07.10 was closed 5-6 days ago

**Comment by ilya-shknaj** [comment]
ok
