### ISSUE TITLE
HW Activites and Static Layout

### ISSUE THREAD

**Issue by amaksimik** [deniotokiari/training-epam-2016#58]
https://github.com/Maksimik/HW/tree/HW-Activity
and Static Layout is on the branch HW-vk

**Comment by ilya-shknaj** [comment]
remove .idea folder

**Comment by ilya-shknaj** [comment]
over links i don't found activities homework and static layout homework

**Comment by amaksimik** [comment]
I fixed
activities homework:
https://github.com/Maksimik/HW/compare/8e4205abfa94d707a793d41c25b7669e84beb3d1...7934850142da9851d03378f40c70c7690fd700d0
static layout homework:
https://github.com/Maksimik/HW/compare/deacc80ddd9bf5bb7764f84f78c43b4ef26a514b...1cc056e14ade2a06b301ba13518275e406de6d1c
and screenshot of my application
![screenshot_2016-10-07-02-05-56](https://cloud.githubusercontent.com/assets/11361951/19175692/9e349492-8c41-11e6-82ce-3d401711ecd7.png)

![screenshot_2016-10-07-02-06-31](https://cloud.githubusercontent.com/assets/11361951/19175701/b228c824-8c41-11e6-9de4-743c578dfecd.png)

**Comment by ilya-shknaj** [comment]
activities homework ok

**Comment by ilya-shknaj** [comment]
in static layout homework you have hardcoded text in layouts. It should be moved to strings.xml file
also you use mipmap folder wrong way - http://stackoverflow.com/questions/28065267/mipmap-vs-drawable-folders
also folder app/src/main/ shouldn't contain any images
