### ISSUE TITLE
HW1 Marharyta_Bakun

### ISSUE THREAD

**Issue by Marhary** [deniotokiari/training-epam-2016#6]
Please check my HW1, I corrected

**Comment by ilya-shknaj** [comment]
@Marhary  your code don't compile. Fix issue and try two more times create conflicts and merge them
also remove .idea directory from git

**Comment by Marhary** [comment]
In class yesterday I was told that all is well ,but I need to merge NAME1 in the master ,because in master I have in the gitignore    . idea ,as in NAME1 .idea/....  and I should make only .idea in name1. It was my problem which  I should correct .

**Comment by kovac777** [comment]
change .gitignore in NAME1 and than merge

**Comment by Marhary** [comment]
I do this ,I wish that you have checked that the gitignore files in master and in name1 are the same, because they were different.Excuse me for troubling

**Comment by IstiN** [comment]
@Marhary which url to your last version of repository? Did you "push" your changes?

**Comment by Marhary** [comment]
Yes,I am push all, and I am checked as you checked ,file name1 was chenged. https://github.com/Marhary/Marharyta_Bakun/blob/name1/SVixx/.gitignore its my name1,now such in master

**Comment by IstiN** [comment]
@Marhary ok, then you need to merge "name1" branch to "master"  branch

**Comment by Marhary** [comment]
I do this

**Comment by Marhary** [comment]
https://github.com/Marhary/Marharyta_Bakun/commits/master

**Comment by IstiN** [comment]
@Marhary you need to remove .idea folder from git. Remove it on file system, commit and push changes.

**Comment by ilya-shknaj** [comment]
@Marhary Steps are a bit different
1) remove .idea from .gitignore file
2) remove folder .idea
3) push changes to git
4) add .idea to .gitignore
5) push updated .gitignore to git

**Comment by Marhary** [comment]
I do  
https://github.com/Marhary/Marharyta_Bakun/commits/master

**Comment by ilya-shknaj** [comment]
@Marhary All right. You removed .idea from SVixx. Do the same for Vixx.
Also try two more times create conflicts and merge them

**Comment by Marhary** [comment]
Project Vixx I accidentally threw there, I should delete it, it's for a new home on Friday,it does not refer to the old HW, it is not even in source tree. 
Can I take that I passed HW1?

**Comment by ilya-shknaj** [comment]
I see that your SVixx project can't be compiled because of you did merge conflicts wrong.
Fix project compilation and try again merge conflicts. After that your HW1 will passed.

**Comment by Marhary** [comment]
I have a difficult situation, the computer hangs and then ceased run a sourcetree, I cant go into the project, I'm afraid that if I delete a program, all branch and whole tree will delete.
I dont know how to be. Ofcource I try to do smth,but I'm not sure what will happen
I am so Sorry to bother you with this problem, it's  very important for me and I'm worried

**Comment by ilya-shknaj** [comment]
@Marhary If you delete source tree or even project on your PC you don't lose nothing, because you can fetch it again from git.

**Comment by Marhary** [comment]
https://github.com/Marhary/Marharyta_Bakun 
 I merge conflicts and project compile now

**Comment by ilya-shknaj** [comment]
ok
