### ISSUE TITLE
HW: 05.10.2016 Zero Activity (SharedPreferences)

### ISSUE THREAD

**Issue by zagart** [deniotokiari/training-epam-2016#60]
Additional info in README.md
[https://github.com/zagart/observer-android/tree/hw05102016sharedpref](https://github.com/zagart/observer-android/tree/hw05102016sharedpref)

**Comment by ilya-shknaj** [comment]
better create separated 'retrieveValue' and 'persistValue' methods for String and Boolean values.
bad solution set value to 'mNextActivity'  without setter
difficult understand code when you use static imports
better set 'persistValue(this, TRUSTED_USER, true);' once when user finish login flow then do that every time when user open MainActivity

**Comment by zagart** [comment]
I got it. Should I fix it to get this HW closed?

**Comment by ilya-shknaj** [comment]
yes, please

**Comment by zagart** [comment]
[Retrieve and persist fixed](https://github.com/zagart/observer-android/commit/9c18289c303e0b1cc245d2e8e5cb3d5d860bc380).

[Static imports fixed.](https://github.com/zagart/observer-android/commit/eb4967ee096ff5b4b655354d82485b7059bc9696)

[Flow end fixed.](https://github.com/zagart/observer-android/commit/9e8697ac38340b8d00b5c65b47c2d685c1cdc5ea)

**Comment by ilya-shknaj** [comment]
ok
