### ISSUE TITLE
HW 07.10.2016

### ISSUE THREAD

**Issue by KarsekaVladimir** [deniotokiari/training-epam-2016#62]
https://github.com/KarsekaVladimir/SocialSample/tree/HW_07.10.2016(reusable_styles%2Ccustom_attributes%2CDraw9Patch)

**Comment by ilya-shknaj** [comment]
you use folder mipmap wrong way. Read documentation and move images to correct folder.
create own Draw9Patch, because i think that i saw that image before

**Comment by KarsekaVladimir** [comment]
Thanks for your comments I fixed it - https://github.com/KarsekaVladimir/SocialSample/commit/aa34cc0d7473535253a8afbce1783a6a63fb96d7
about  - Draw9Patch.
I dowloaded it here - https://goo.gl/x5AKBU
made  Draw9 here - https://romannurik.github.io/AndroidAssetStudio/nine-patches.html
https://www.dropbox.com/s/fggkt3p4wr5v9zu/Draw9Patch.png?dl=0
https://www.dropbox.com/s/5bouk7xsd97xwdz/Screen.png?dl=0

**Comment by ilya-shknaj** [comment]
ok
