### ISSUE TITLE
HW 05.10.2016 Layout

### ISSUE THREAD

**Issue by alxanko** [deniotokiari/training-epam-2016#64]
Alexey Khanko
https://github.com/chelsenok/layout
https://github.com/chelsenok/layout/blob/master/Screenshot_1475845693.png

**Comment by ilya-shknaj** [comment]
TableLayout deprecated. Try to use another containers.
you use mipmap folder wrong way. Read documentation and move images to correct folder

**Comment by ilya-shknaj** [comment]
sorry, TableLayout not deprecated, it is just old widget. 
But whatever, try use another containers for parts of your views

**Comment by alxanko** [comment]
https://github.com/chelsenok/layout/commit/fc4c45129abc1e1fbc8b66755861040c3e3097f1
ok, i just now change it to Linear containers

**Comment by ilya-shknaj** [comment]
good
