### ISSUE TITLE
Both homeworks (in branches)

### ISSUE THREAD

**Issue by alaksiej-karalou** [deniotokiari/training-epam-2016#65]
https://github.com/Aliaksei-Karaliou/EpamHomeTasks

**Comment by ilya-shknaj** [comment]
please specify which homeworks you done. 
I don't found homework over provided link

**Comment by alaksiej-karalou** [comment]
Sorry, it is not correct link, correct link is there (layouts and shared preferences are in specific branches)
https://github.com/Aliaksei-Karaliou/EpamHomeWork

**Comment by ilya-shknaj** [comment]
1) remove .idea folder
2) you never will have images like background_avatar_profile_fb.png in production. use separated images for background and for avatar

**Comment by alaksiej-karalou** [comment]
https://github.com/Aliaksei-Karaliou/EpamHomeWork/commit/33c00bd0823339a2223da7431c2ef9bfecfa1c43

**Comment by ilya-shknaj** [comment]
I still see .idea folder in your git. - https://github.com/Aliaksei-Karaliou/EpamHomeWork/tree/master/.idea
It's also wrong way create that background https://github.com/Aliaksei-Karaliou/EpamHomeWork/blob/33c00bd0823339a2223da7431c2ef9bfecfa1c43/app/src/main/res/drawable/background_profile_fb.png
Right way use normal background without any gaps, and overlay that background by avatar

**Comment by alaksiej-karalou** [comment]
1. .idea folder has removed there https://github.com/Aliaksei-Karaliou/EpamHomeWork/commit/6dc00f829c2c7ed4afd90b9bd52aa0f4b878e095
2. Background image updated (I had not found full original image of the background, i use another background) there https://github.com/Aliaksei-Karaliou/EpamHomeWork/commit/52b35eb017461142ec24819675f2ef75ceca09df

**Comment by ilya-shknaj** [comment]
ok
