### ISSUE TITLE
HW 07.10.16 Layout

### ISSUE THREAD

**Issue by qerlly** [deniotokiari/training-epam-2016#66]
https://github.com/qerlly/Vk
https://github.com/qerlly/Vk/blob/master/README.md

**Comment by qerlly** [comment]
![jl5xn4iznzc](https://cloud.githubusercontent.com/assets/22331398/19203492/40d130e0-8ce0-11e6-8337-75211be3c1ae.jpg)
![5ljmftbfkyu](https://cloud.githubusercontent.com/assets/22331398/19203489/40c0f270-8ce0-11e6-9a36-cf2248e5831c.jpg)
![fmswmnbn_ms](https://cloud.githubusercontent.com/assets/22331398/19203491/40ca29da-8ce0-11e6-9836-c3df0c0db6c0.jpg)
![gwekgvos3qk](https://cloud.githubusercontent.com/assets/22331398/19203490/40c51e2c-8ce0-11e6-8e79-abd317f7dbcd.jpg)

**Comment by ilya-shknaj** [comment]
why image 4chimage-web.png in app/src/main/ folder?
move hardcoded text to strings.xml

**Comment by qerlly** [comment]
https://github.com/qerlly/Vk/commit/a1c12230e677683a7e68f27ba344636da947f693

**Comment by ilya-shknaj** [comment]
please also fix hardcoded text in drawing_layout.xml

**Comment by qerlly** [comment]
Done
https://github.com/qerlly/Vk/commit/8a592a3ea006865f083d8d301a7e5018b75a3c89

**Comment by ilya-shknaj** [comment]
i think you project can not be compiled because you have duplicates of strings

**Comment by qerlly** [comment]
Sorry I did not notice, all fixed https://github.com/qerlly/Vk/commit/fd165663558f06d3e3a3230e1a1f3e6dd06fb237

**Comment by ilya-shknaj** [comment]
ok
