### ISSUE TITLE
HW: 07,10,2016

### ISSUE THREAD

**Issue by Pahanbl4** [deniotokiari/training-epam-2016#67]
https://github.com/Pahanbl4/home
![screenshot_1](https://cloud.githubusercontent.com/assets/22370107/19192517/2652b968-8caf-11e6-9652-b3ebdbc4e08c.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/22370107/19192520/281c8ef4-8caf-11e6-863d-c74e0d47de75.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/22370107/19192522/29330c46-8caf-11e6-946b-9cc7fd9ec33c.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/22370107/19192524/2afda7d4-8caf-11e6-85b3-d56a82af1549.png)

**Comment by ilya-shknaj** [comment]
please specify link. I don't find homework over provided link

**Comment by ilya-shknaj** [comment]
?

**Comment by Pahanbl4** [comment]
i'm sorri.
https://github.com/Pahanbl4/home/tree/vk/houmi22

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that on class in previous week)
