### ISSUE TITLE
Layouts.

### ISSUE THREAD

**Issue by Hanna-Kokhanava** [deniotokiari/training-epam-2016#7]
Good morning! I have a question about layouts. 

So, for example we have a RelativeLayout as a parent and there are a lot of nested linear layouts (vertical or horizontal, it doesn't matter) in it. And these linear layouts also can contain nested linear layouts.

Is it a good idea to build such structure or should we use another layouts, for example FrameLayout with its gravity property? Because it seems easier to me to combine linear layouts like a blocks in parent Relative Layout.

**Comment by IstiN** [comment]
Ideally avoid using LinearLayout with weight inside LinearLayouts and RelativeLayouts inside RelativeLayouts. LinearLayouts and RelativeLayouts should be on bottom level of hierarchy for best performance.
Your goal now to play with it as much as possible in different cases.

**Comment by Hanna-Kokhanava** [comment]
Thank you for replying so quickly. Issue can be closed.
