### ISSUE TITLE
HW10.10.2016

### ISSUE THREAD

**Issue by kovac777** [deniotokiari/training-epam-2016#73]
https://github.com/kovac777/HW10.10.2016
Maksim Vinnik

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that today on class)

**Comment by kovac777** [comment]
I'm sorry, but I was missing today. Could You briefly describe what I need to do

**Comment by ilya-shknaj** [comment]
1) open branch with homework in browser, for instance https://github.com/kovac777/HW10.10.2016
2) add to url /compare (https://github.com/kovac777/HW10.10.2016/compare)
3)  put two commits SHA (before start homework and when homework done). commits SHA you can get from sourceTree or via https://github.com/kovac777/HW10.10.2016/commits/master
4) provide me result link. Over that link i should see differences, where differences is homework

**Comment by ilya-shknaj** [comment]
if you did your homework in single commit, you can provide link to that commit

**Comment by kovac777** [comment]
I was doing my homework in the new project and every commit corresponds to a paragraph homework. 

For example:

HW 10.10.2016
1. Implement some object.
2. Write units test for that object
3. Mock part/fully behaviour of that object. (mockito, robolectric)
4. Write instrumentationTests (expresso, robotium )
5. Implement button which visibility depends of private field in activity. Mock that private object.

my commits:
https://github.com/kovac777/HW10.10.2016/commit/e602595ae5552c50060500204e2841033b12d069
https://github.com/kovac777/HW10.10.2016/commit/f4fd55a84923d1b662fc18e5235e5e39f4156b8e
https://github.com/kovac777/HW10.10.2016/commit/7231ec00c9b912d63a807fcf134c4f408e719c90
https://github.com/kovac777/HW10.10.2016/commit/4e70baaa2ce0371e603530b0b036b4cebded7e96
https://github.com/kovac777/HW10.10.2016/commit/1565f22dd93a349c527c86d2cb0612dcd537944b

**Comment by ilya-shknaj** [comment]
it's good, but click five times take time. 
Also it's one hometask with subtask, thats why I wanna see all that your implement for that homework in single page

**Comment by kovac777** [comment]
https://github.com/kovac777/HW-10.10.2016/commit/63adcb77bfaed558bea2ff57bdb6c94880f8cca3

**Comment by ilya-shknaj** [comment]
in setUp method you can init all stuff that you need, but don't write some test logic in that method, because that method call before every test

**Comment by kovac777** [comment]
b8031e5749306e89039337465854baa107abf406

**Comment by kovac777** [comment]
https://github.com/kovac777/HW-10.10.2016/commit/b8031e5749306e89039337465854baa107abf406
fixed

**Comment by ilya-shknaj** [comment]
i am still see validations in HumanTest

**Comment by kovac777** [comment]
https://github.com/kovac777/HW-10.10.2016/commit/69e83c64d4de8445347ac31cfe8ab8242dfa55e8

**Comment by ilya-shknaj** [comment]
ok
