### ISSUE TITLE
HW ZeroActivity 03.10.2016

### ISSUE THREAD

**Issue by kitaisreal** [deniotokiari/training-epam-2016#9]
New repository for homework
https://github.com/kitaisreal/ZeroActivityHW

**Comment by IstiN** [comment]
Great:
Application will work incorrect if you turn on option to destroy activity in developers settings.

What if I would like to remember what last screen was opened if I did not finish flow?
NOTE:SharedPreferences.

**Comment by kitaisreal** [comment]
Fixed SharedPreferences

**Comment by ilya-shknaj** [comment]
bad solution override onBackPressed method. Because in real application sometimes you can't know previous activity

**Comment by ilya-shknaj** [comment]
use flags https://developer.android.com/reference/android/content/Intent.html

**Comment by kitaisreal** [comment]
Fixed https://github.com/kitaisreal/ZeroActivityHW (fixed onBackPressed, added flags)

**Comment by ilya-shknaj** [comment]
ok
