### ISSUE TITLE
HW 10.10.16 (Button testing)

### ISSUE THREAD

**Issue by alaksiej-karalou** [deniotokiari/training-epam-2016#94]
https://github.com/Aliaksei-Karaliou/Testing

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that today on class)

**Comment by alaksiej-karalou** [comment]
https://github.com/Aliaksei-Karaliou/Testing/commit/93c2a39984fc20370309bed739b47c4e2b7a61c5

.idea was removed in later commits (https://github.com/Aliaksei-Karaliou/Testing/compare/93c2a39984fc20370309bed739b47c4e2b7a61c5...6605b8b2117270905068be0335c1c7e85570fbe4)

**Comment by ilya-shknaj** [comment]
ok
