### ISSUE TITLE
HW:10.10.16

### ISSUE THREAD

**Issue by Pahanbl4** [deniotokiari/training-epam-2016#95]
https://github.com/Pahanbl4/Test22

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that today on class)

**Comment by ilya-shknaj** [comment]
?

**Comment by Pahanbl4** [comment]
HW 10.10.2016

Implement some object.
Write units test for that object
Mock part/fully behaviour of that object. (mockito, robolectric)
Write instrumentationTests (expresso, robotium )
Implement button which visibility depends of private field in activity. Mock that private object.

**Comment by ilya-shknaj** [comment]
please provide link which will show me differences in one page (I demonstrate how to do that 6 days ago on class)
